### ISSUE TITLE
Notify user of criteria misses (isEmail, password Length) on sign up

### ISSUE THREAD

**Issue by sarahdurks** [sarahdurks/fullstack-pokemon-game#27]
current sign up process does not specify what went wrong to the user if email format is invalid or password is too short.

terminal errors only, alert to user is generic

ValidationErrorItem {
      message: 'Validation len on password failed',
      type: 'Validation error',

should update to specify

**Comment by sarahdurks** [comment]
@down-dive we can also coordinate on this one! basically, letting the user know why their login criteria is off.

We may need to get the heroku issues fixed first though.

**Comment by down-dive** [comment]
Sounds good!
